/camera/image_projection:
  ros__parameters:
    camera.extrinsic_camera_calibration.bottom_x: 150
    camera.extrinsic_camera_calibration.bottom_y: 151
    camera.extrinsic_camera_calibration.top_x: 72
    camera.extrinsic_camera_calibration.top_y: 7

