/camera/image_projection:
  ros__parameters:
    camera.extrinsic_camera_calibration.top_x: 220  
    camera.extrinsic_camera_calibration.top_y: 50
    camera.extrinsic_camera_calibration.bottom_x: 400  
    camera.extrinsic_camera_calibration.bottom_y: 180



