---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_l: 150
          hue_h: 179
          saturation_l: 0
          saturation_h: 70
          lightness_l: 150
          lightness_h: 255

        yellow:
          hue_l: 20
          hue_h: 90
          saturation_l: 50
          saturation_h: 255
          lightness_l: 80
          lightness_h: 255