---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_l: 0
          hue_h: 179
          saturation_l: 0
          saturation_h: 50
          lightness_l: 200
          lightness_h: 255

        yellow:
          hue_l: 25
          hue_h: 35
          saturation_l: 100
          saturation_h: 255
          lightness_l: 100
          lightness_h: 255
