---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_l: 44
          hue_h: 120
          saturation_l: 0
          saturation_h: 255
          lightness_l: 249
          lightness_h: 255

        yellow:
          hue_l: 8
          hue_h: 50
          saturation_l: 0
          saturation_h: 255
          lightness_l: 66
          lightness_h: 255